import type { Config } from "tailwindcss";

export default {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                brand: "hsl(var(--brand))",
                "brand-foreground": "hsl(var(--brand-foreground))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                muted: "hsl(var(--muted))",
                "muted-foreground": "hsl(var(--muted-foreground))",
                card: "hsl(var(--card))",
                "card-foreground": "hsl(var(--card-foreground))",
                popover: "hsl(var(--popover))",
                "popover-foreground": "hsl(var(--popover-foreground))",
                primary: "hsl(var(--primary))",
                "primary-foreground": "hsl(var(--primary-foreground))",
                secondary: "hsl(var(--secondary))",
                "secondary-foreground": "hsl(var(--secondary-foreground))",
                destructive: "hsl(var(--destructive))",
                "destructive-foreground": "hsl(var(--destructive-foreground))",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                sidebar: {
                    DEFAULT: "hsl(var(--sidebar-background))",
                    foreground: "hsl(var(--sidebar-foreground))",
                    primary: "hsl(var(--sidebar-primary))",
                    "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
                    accent: "hsl(var(--sidebar-accent))",
                    "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
                    border: "hsl(var(--sidebar-border))",
                    ring: "hsl(var(--sidebar-ring))",
                },
                // Simplified colors for student platform
                'text': {
                    primary: 'hsl(var(--foreground))',
                    secondary: 'hsl(var(--muted-foreground))',
                    muted: 'hsl(var(--muted-foreground))',
                },
                'bg': {
                    card: 'hsl(var(--card))',
                    secondary: 'hsl(var(--secondary))',
                },
                'border-card': 'hsl(var(--border))',
                'border-subtle': 'hsl(var(--border))',
                'accent-warm': 'hsl(var(--primary))',
                'primary-muted': 'hsl(var(--muted))',
                'primary-light': 'hsl(var(--brand))',
            },
            fontFamily: {
                sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
                mono: ['var(--font-mono)', 'monospace'],
                display: ['var(--font-sans)', 'system-ui', 'sans-serif'],
            },
            borderRadius: {
                'sm': '0.375rem',
                'md': '0.5rem',
                'lg': '0.75rem',
                '2xl': '1rem',
                '3xl': '1.5rem',
            },
            boxShadow: {
                'none': 'none',
                'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
                'sm': '0 2px 4px 0 rgba(0, 0, 0, 0.08)',
                'md': '0 4px 12px 0 rgba(0, 0, 0, 0.1)',
                'lg': '0 10px 24px 0 rgba(0, 0, 0, 0.12)',
                'xl': '0 20px 40px 0 rgba(0, 0, 0, 0.15)',
            },
            letterSpacing: {
                'tighter': '-0.05em',
                'tight': '-0.025em',
                'normal': '0',
                'wide': '0.025em',
                'wider': '0.05em',
                'widest': '0.1em',
            },
        },
    },
    plugins: [],
} satisfies Config;
