"""add project type to github_projects

Revision ID: 32143cf0314b
Revises: a09440b522c1
Create Date: 2026-02-21 10:05:10.715841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32143cf0314b'
down_revision: Union[str, Sequence[str], None] = 'a09440b522c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_projects', sa.Column('project_type', sa.String(), nullable=False, server_default='PROJECT'))
    op.create_index(op.f('ix_github_projects_project_type'), 'github_projects', ['project_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_projects_project_type'), table_name='github_projects')
    op.drop_column('github_projects', 'project_type')
    # ### end Alembic commands ###
