"""Initial schema

Revision ID: a09440b522c1
Revises: 
Create Date: 2026-02-20 22:32:45.810396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a09440b522c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_time_spent', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('github_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('repo_owner', sa.String(), nullable=True),
    sa.Column('repo_name', sa.String(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('download_url', sa.String(), nullable=False),
    sa.Column('live_url', sa.String(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('technical_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tools_used', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('concepts_used', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sub_domain', sa.String(), nullable=True),
    sa.Column('case_study', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('solution_description', sa.Text(), nullable=True),
    sa.Column('prerequisites', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('prerequisites_text', sa.Text(), nullable=True),
    sa.Column('estimated_min_time', sa.Integer(), nullable=False),
    sa.Column('estimated_max_time', sa.Integer(), nullable=False),
    sa.Column('deliverables', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('supposed_deadline', sa.String(), nullable=True),
    sa.Column('optional_extensions', sa.Text(), nullable=True),
    sa.Column('requirements', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('requirements_text', sa.Text(), nullable=True),
    sa.Column('evaluation_criteria', sa.Text(), nullable=True),
    sa.Column('qa_status', sa.String(), nullable=False),
    sa.Column('qa_feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_projects_difficulty'), 'github_projects', ['difficulty'], unique=False)
    op.create_index(op.f('ix_github_projects_domain_id'), 'github_projects', ['domain_id'], unique=False)
    op.create_index(op.f('ix_github_projects_is_active'), 'github_projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_github_projects_language'), 'github_projects', ['language'], unique=False)
    op.create_index(op.f('ix_github_projects_slug'), 'github_projects', ['slug'], unique=True)
    op.create_index(op.f('ix_github_projects_stars'), 'github_projects', ['stars'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('related_project_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_domain_id'), 'projects', ['domain_id'], unique=False)
    op.create_table('github_project_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('github_project_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist', postgresql.ARRAY(sa.Boolean()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['github_project_id'], ['github_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_project_progress_github_project_id'), 'github_project_progress', ['github_project_id'], unique=False)
    op.create_index(op.f('ix_github_project_progress_status'), 'github_project_progress', ['status'], unique=False)
    op.create_index(op.f('ix_github_project_progress_user_id'), 'github_project_progress', ['user_id'], unique=False)
    op.create_table('project_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('last_timer_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_progress_project_id'), 'project_progress', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_progress_status'), 'project_progress', ['status'], unique=False)
    op.create_index(op.f('ix_project_progress_user_id'), 'project_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_progress_user_id'), table_name='project_progress')
    op.drop_index(op.f('ix_project_progress_status'), table_name='project_progress')
    op.drop_index(op.f('ix_project_progress_project_id'), table_name='project_progress')
    op.drop_table('project_progress')
    op.drop_index(op.f('ix_github_project_progress_user_id'), table_name='github_project_progress')
    op.drop_index(op.f('ix_github_project_progress_status'), table_name='github_project_progress')
    op.drop_index(op.f('ix_github_project_progress_github_project_id'), table_name='github_project_progress')
    op.drop_table('github_project_progress')
    op.drop_index(op.f('ix_projects_domain_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_github_projects_stars'), table_name='github_projects')
    op.drop_index(op.f('ix_github_projects_slug'), table_name='github_projects')
    op.drop_index(op.f('ix_github_projects_language'), table_name='github_projects')
    op.drop_index(op.f('ix_github_projects_is_active'), table_name='github_projects')
    op.drop_index(op.f('ix_github_projects_domain_id'), table_name='github_projects')
    op.drop_index(op.f('ix_github_projects_difficulty'), table_name='github_projects')
    op.drop_table('github_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('domains')
    # ### end Alembic commands ###
